<?php
require_once __DIR__.'/../conexao.php'; require_once __DIR__.'/../garantir_cargas.php'; require_once __DIR__.'/resposta.php'; require_once __DIR__.'/sessao_helper.php';
try { garantirTabelaCargas($conexao); } catch (Throwable $erro) { responderErro(500, $erro->getMessage()); }
$usuario=exigirUsuarioAutenticado(); $metodo=$_SERVER['REQUEST_METHOD']??'GET';
if($metodo==='GET'){ $busca=trim((string)($_GET['busca']??''));$status=trim((string)($_GET['status']??''));$sql='SELECT c.*,t.prefixo_trem FROM cargas c LEFT JOIN trens t ON t.id_trem=c.id_trem WHERE 1';$tipos='';$args=[];if($busca!==''){$sql.=' AND (c.codigo_carga LIKE ? OR c.descricao LIKE ? OR c.origem LIKE ? OR c.destino LIKE ? OR t.prefixo_trem LIKE ?)';$tipos.='sssss';$x='%'.$busca.'%';$args=[$x,$x,$x,$x,$x];}if($status!==''){$sql.=' AND c.status_carga=?';$tipos.='s';$args[]=$status;}$sql.=' ORDER BY c.atualizado_em DESC';$s=$conexao->prepare($sql);if($args)$s->bind_param($tipos,...$args);$s->execute();$r=$s->get_result();$c=[];while($l=$r->fetch_assoc())$c[]=$l;$s->close();responderJson(200,['total'=>count($c),'cargas'=>$c]); }
if(!in_array($usuario['cargo'],['gestor','maquinista'],true))responderErro(403,'Somente gestores e maquinistas podem alterar cargas.');
$d=lerDadosRequisicao();$codigo=strtoupper(trim((string)($d['codigo_carga']??'')));$descricao=trim((string)($d['descricao']??''));$origem=trim((string)($d['origem']??''));$destino=trim((string)($d['destino']??''));$peso=(float)($d['peso_kg']??0);$status=trim((string)($d['status_carga']??'aguardando'));$idTrem=(int)($d['id_trem']??0);$chegada=$d['chegada_prevista']??null;
if(!preg_match('/^[A-Z0-9-]{3,20}$/',$codigo)||$descricao===''||$origem===''||$destino===''||$peso<=0||!in_array($status,['aguardando','em_transito','entregue','atrasada','cancelada'],true))responderErro(422,'Preencha os dados da carga corretamente.');
if($metodo==='POST'){$s=$conexao->prepare('INSERT INTO cargas(codigo_carga,descricao,peso_kg,origem,destino,id_trem,status_carga,chegada_prevista) VALUES(?,?,?,?,?,?,?,?)');$s->bind_param('ssdssiss',$codigo,$descricao,$peso,$origem,$destino,$idTrem,$status,$chegada);$s->execute();$s->close();responderJson(201,['mensagem'=>'Carga cadastrada com sucesso.']);}
responderErro(405,'Metodo nao permitido.');

